name: Update CNX Pack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt install -y unzip jq

      - name: Grab latest CNX Pack
        run: |
          release_info=$(curl -s https://api.github.com/repos/AMSNX/CNX/releases/latest)
          file_name=$(echo "$release_info" | jq -r '.assets[0].name')
          curl -LO https://github.com/AMSNX/CNX/releases/latest/download/"$file_name"
          unzip $file_name
          rm $file_name

      - name: Apply sigpatches
        run: |
          awoo_installer=$(curl -s https://api.github.com/repos/Huntereb/Awoo-Installer/releases/latest)
          awoo_zip=$(echo "$awoo_installer" | jq -r '.assets[0].name')
          curl -LO https://github.com/Huntereb/Awoo-Installer/releases/latest/download/"$awoo_zip"
          unzip $awoo_zip
          rm $awoo_zip

      - name: Compress everything
        run: |
          tar -czvf cyber_destrava.tar.gz *
          find . -type f ! -name 'cyber_destrava.tar.gz' -exec rm {} +

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Commit and push changes
        run: |
          git clone https://github.com/cybercampos/destrava-switch/
          mv cyber_destrava.tar.gz destrava-switch/
          cd destrava-switch/
          git add .
          git commit -m "Update CNX Pack"
          git push -u origin main
