name: Update CNX Pack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      token: ${{ secrets.CYBER_BOT_KEY }}
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt install -y unzip jq git-lfs

      - name: Grab latest CNX Pack
        run: |
          release_info=$(curl -s https://api.github.com/repos/AMSNX/CNX/releases/latest)
          file_name=$(echo "$release_info" | jq -r '.assets[0].name')
          curl -LO https://github.com/AMSNX/CNX/releases/latest/download/"$file_name"
          unzip $file_name
          rm $file_name

      - name: Apply sigpatches
        run: |
          awoo_installer=$(curl -s https://api.github.com/repos/Huntereb/Awoo-Installer/releases/latest)
          awoo_zip=$(echo "$awoo_installer" | jq -r '.assets[0].name')
          curl -LO https://github.com/Huntereb/Awoo-Installer/releases/latest/download/"$awoo_zip"
          unzip $awoo_zip
          rm $awoo_zip

      - name: Compress everything
        run: |
          rm cyber_destrava.tar.gz
          tar -czvf cyber_destrava.tar.gz *
          find . -type f ! -name 'cyber_destrava.tar.gz' -exec rm {} +
          
      - name: Push to Repo
        run: |
          git init
          git lfs install
          git branch -M main
          git config --global user.email "cybercampos.assistencia@gmail.com"
          git config --global user.name "CyberBot"
          git config --global init.default branch main
          git remote add origin https://PixGuy:${{ secrets.GIT_PUSH_KEY }}@github.com/cybercampos/destrava-switch/
          git pull https://github.com/cybercampos/destrava-switch/ main
          git lfs track "*.tar.gz"
          git add *
          git stash
          git commit -m "Atualizar o CNX"
          git push -u origin main
